### ISSUE TITLE
APP NOT OPENING ON TV CONNECTION ERROR

### ISSUE THREAD

**Issue by ajdeshmane0007** [song940/mytv#1]
Connection error

**Comment by lsongdev** [comment]
感谢反馈

遇到 `CONNECTION ERROR` 一般是网络问题导致无法获取直播源(or EPG) 数据，程序内部默认使用的是 <https://raw.githubusercontent.com/YueChan/Live/main/IPTV.m3u> 托管在 <https://raw.githubusercontent.com> 所以国内网络原因可能会无法获取。

解决办法：

1. 你可以尝试解决网络问题，主要是对 raw.githubusercontent.com 的访问。
2. 在应用启动的加载界面，按 <kbd>back 返回</kbd> 键进入「设置」界面，左侧选择「直播源」来添加自定义的直播源。

或者你也可以确认一下你能否正常访问 GitHub 加速代理地址 <https://mirror.ghproxy.com>，如果能够访问可以在直播源前面添加这个代理地址来解决访问问题 (如 https://mirror.ghproxy.com/https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u)。

**应用目前仍在快速迭代中，可能存在较多的问题需要解决，谨慎使用。**
